### ISSUE TITLE
Where is gone the Firebase Admin SDK ?

### ISSUE THREAD

**Issue by LM450N** [firebase/quickstart-java#7]
Until yesterday, we could find the Firebase Admin SDK on [Maven repository](http://mvnrepository.com/artifact/com.firebase). We can still install it but [the GitHub repo has disappeared](https://github.com/firebase/firebase-clients/java_admin_sdk).

I have an issue with the [GSON](https://github.com/google/gson) dependency used by Firebase Admin SDK. It is using [GSON version 2.6.2 which has an configuration issue](https://github.com/google/gson/issues/819). Please, update it to 2.7.0 or higher if possible.

Also, can I find some news about Firebase Admin Java SDK somewhere? I can't think Firebase team leaving its lovely community in the dark. 🕵️

**Comment by samtstern** [comment]
@jwngr what happened to that github repo?

**Comment by jwngr** [comment]
Hey @LM450N, let's see if I can get you some answers:

> Until yesterday, we could find the Firebase Admin SDK on Maven repository.

The link you shared in not actually the real Maven repository, it just a mirror of it. The link you want is [this one](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.firebase%22%20AND%20a%3A%22firebase-admin%22).

> We can still install it but the GitHub repo has disappeared.

That repo is a private repo which is why you cannot see it. How did you even get the URL for that in the first place?

> I have an issue with the GSON dependency used by Firebase Admin SDK. It is using GSON version 2.6.2 which has an configuration issue. Please, update it to 2.7.0 or higher if possible.

I will look into upgrading it.

> Also, can I find some news about Firebase Admin Java SDK somewhere? I can't think Firebase team leaving its lovely community in the dark. 

The release notes are [here](https://firebase.google.com/support/release-notes/admin/java), a docs guide starts [here](https://firebase.google.com/docs/admin/setup), the API reference is [here](https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/package-summary), and releases are tweeted from [@FirebaseRelease](https://twitter.com/firebaserelease). I even wrote a [blog post](https://firebase.googleblog.com/2016/11/bringing-firebase-to-your-server.html) on the Admin SDKs just last week. Is there something else you'd like to see from us?

**Comment by jwngr** [comment]
Also, I should note, the source code for the Admin Java SDK is not open source, which is why you cannot access that.

**Comment by LM450N** [comment]
Thank you for your answers. It's perfect! 💯 

Today I tried to use this SDK on App Engine and I don't really understand why it's throwing the _"IllegalStateException: This feature is only available to backend instances."_ 

I mean, why App Engine instance is not considered as a backend? I'm using it only to expose the datastore through a REST API. My purpose is get user information from Firebase on App Engine. [This could be a solution](http://yawp.io/blog/2016/06/06/yawp-firebase-30-appengine) but it allows only to verify the OAuth token.

There is a setting parameter to define or it's simply not possible? I guess it's not the place to discuss about it 😄 .

**Comment by jwngr** [comment]
What version of the Admin Java SDK are you using? We released a fix today with the `4.0.2` release which added back in support for Java 7, which is what GAE Standard runs on. Can you try using the latest release and see if that works for you?

**Comment by LM450N** [comment]
In fact I was using the _"firebase-server-sdk"_ meanwhile the new library to be compatible with Java 7. I just now tried with the _"firebase-admin-sdk" (4.0.2)_ and I got the same error. Here a part of the StackTrace.

<img width="823" alt="capture d ecran 2016-11-16 a 09 55 30" src="https://cloud.githubusercontent.com/assets/2325091/20340768/72771eda-abe3-11e6-9c4c-b2b7ddab6464.png">

**Comment by jwngr** [comment]
Ahhh, I think I know what is going on. Are you by chance using GAE automatic scaling? Unfortunately, the Firebase Java SDK currently only supports manual scaling. You can read [this Stack Overflow](http://stackoverflow.com/questions/38078514/java-lang-illegalstateexception-this-feature-is-only-available-to-backend-insta) question for some more info.

**Comment by LM450N** [comment]
Yes my App Engine app is automatically scaled. I've read threads talking about scaling but not detailed as this one. I'll try it asap. Please, as soon as the teleportation will be available, call me, I'll send you a 🍺 .

Thank you a lot for your help!

**Comment by jwngr** [comment]
Cheers, glad we got everything figured out 🍻
